name: mobipkg_tools
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  
dependencies:
  args: ^2.4.0
  logger: ^1.3.0
  path: ^1.8.3
  process_run: ^0.12.5+3
