name: Show ffmpeg deps to test mobipkg_tools
run-name: Get ffmpeg info with mobipkg_tools

on:
  - push

jobs:
  show-ffmpeg-deps:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Install dart'
        uses: 'dart-lang/setup-dart@v1'
        with:
          sdk: 'stable'
      - name: 'Install dependencies'
        run: |
          dart pub get
      - name: 'Run to show info'
        run: |
          dart --version
          dart run bin/mobipkg_tools.dart --help
      - name: 'Run to show info'
        run: |
          dart run bin/mobipkg_tools.dart dep ffmpeg
      - name: 'Run to show info again, the second time have file cached'
        run: |
          dart run bin/mobipkg_tools.dart dep ffmpeg